### ISSUE TITLE
Head effector for fullbodyIK

### ISSUE THREAD

**Issue by KospY** [Unity-Technologies/animation-jobs-samples#8]
This solution could be so nice for VR, but it lack an essential thing, an head effector (position and rotation).
Hope this is something easy/fast to implement.
For more information: https://forum.unity.com/threads/animation-c-jobs-in-2018-2a5.525012/page-3#post-3695041

**Comment by romainf-unity** [comment]
Hello!

There is already a look at effector on the Fullbody IK example: https://github.com/Unity-Technologies/animation-jobs-samples/blob/master/Assets/animation-jobs-samples/Samples/Scripts/FullBodyIK/LookAtEffector.cs

By default the weights are set to 0.0, but if you increase that, you'll see that the body, head, eyes will follow the effector.

**Comment by KospY** [comment]
I'm not looking into a look at effector. For VR, the goal is to sync the player head position (the headset) with the head of the character. It should work the same as an hand effector (set position and rotation).
For example if the player crouch IRL the character IK must follow and kneel accordingly.
Right now the only solution is to use third parties solution for this (take a look at VRIK for example), but I'm really interested to use a simplier and effective solution like animation jobs  :)

**Comment by romainf-unity** [comment]
I understand, and I think you would be able to do that using the Animation Jobs.

That being said, it doesn't seem straightforward. If I understood well, you want the head to drive the lower body, which means that moving the head will move the hips accordingly.

But unfortunately, it's not something that we'll do in the samples since they're mainly here to understand how the Animation Jobs work and give some examples for simple(-ish) cases.

**Comment by romainf-unity** [comment]
This issue is not a bug with the samples, it's a feature that is too big to be implemented here.
